// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyc7NIh6ouOCUOWw2Wg938EzRgBAomdko',
    appId: '1:815961107669:web:8d16b0cc9b0d3cb81fc65c',
    messagingSenderId: '815961107669',
    projectId: 'kutuphane-2d1f0',
    authDomain: 'kutuphane-2d1f0.firebaseapp.com',
    storageBucket: 'kutuphane-2d1f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRbtRmFlnGDtVFKuLF1tmBJ73eRAJlCc',
    appId: '1:815961107669:android:048d6cb38a929bf01fc65c',
    messagingSenderId: '815961107669',
    projectId: 'kutuphane-2d1f0',
    storageBucket: 'kutuphane-2d1f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcab6NzT_2OY4ifXgwfdfGufG1JFc_28U',
    appId: '1:815961107669:ios:3ede3db9bbf2726c1fc65c',
    messagingSenderId: '815961107669',
    projectId: 'kutuphane-2d1f0',
    storageBucket: 'kutuphane-2d1f0.appspot.com',
    iosBundleId: 'com.example.ilkproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcab6NzT_2OY4ifXgwfdfGufG1JFc_28U',
    appId: '1:815961107669:ios:113155221b39a61d1fc65c',
    messagingSenderId: '815961107669',
    projectId: 'kutuphane-2d1f0',
    storageBucket: 'kutuphane-2d1f0.appspot.com',
    iosBundleId: 'com.example.ilkproje.RunnerTests',
  );
}
